### ISSUE TITLE
(LogManager): Same file processing information keeps being written to config.tlog infinitely.

### ISSUE THREAD

**Issue by adamchen-cognitohealth** [aws-greengrass/aws-greengrass-log-manager#109]
**Describe the bug**
Same file processing information keeps being written to config.tlog infinitely. At the same time, kworker process occupied lots of CPU resources.

**To Reproduce**
Use LogManager to handle logs of greengrass and custom components.

**Expected behavior**
Same file processing information of LogManager should not be written to config.tlog repeatedly which seems to cause high CPU usage.

**Actual behavior**
The same `currentComponentFileProcessingInformation` keeps written to `/greengrass/v2/config/config.tlog` repeatedly in a very high rate.
```
{"TS":1666597838548,"TP":["services","aws.greengrass.LogManager","runtime","currentComponentFileProcessingInformation","System","currentProcessingFileName"],"W":"timestampUpdated","V":null}
{"TS":1666597838548,"TP":["services","aws.greengrass.LogManager","runtime","currentComponentFileProcessingInformation","System","currentProcessingFileStartPosition"],"W":"timestampUpdated","V":null}
{"TS":1666597838548,"TP":["services","aws.greengrass.LogManager","runtime","currentComponentFileProcessingInformation","System","currentProcessingFileLastModified"],"W":"timestampUpdated","V":null}
{"TS":1666597838598,"TP":["services","aws.greengrass.LogManager","runtime","currentComponentFileProcessingInformation","box_configuration","currentProcessingFileName"],"W":"timestampUpdated","V":null}
{"TS":1666597838598,"TP":["services","aws.greengrass.LogManager","runtime","currentComponentFileProcessingInformation","box_configuration","currentProcessingFileStartPosition"],"W":"timestampUpdated","V":null}
{"TS":1666597838598,"TP":["services","aws.greengrass.LogManager","runtime","currentComponentFileProcessingInformation","box_configuration","currentProcessingFileLastModified"],"W":"timestampUpdated","V":null}
{"TS":1666597838599,"TP":["services","aws.greengrass.LogManager","runtime","currentComponentFileProcessingInformation","io.cognitohealth.DataGenerationV2","currentProcessingFileName"],"W":"timestampUpdated","V":null}
{"TS":1666597838599,"TP":["services","aws.greengrass.LogManager","runtime","currentComponentFileProcessingInformation","io.cognitohealth.DataGenerationV2","currentProcessingFileStartPosition"],"W":"timestampUpdated","V":null}
{"TS":1666597838599,"TP":["services","aws.greengrass.LogManager","runtime","currentComponentFileProcessingInformation","io.cognitohealth.DataGenerationV2","currentProcessingFileLastModified"],"W":"timestampUpdated","V":null}
{"TS":1666597838599,"TP":["services","aws.greengrass.LogManager","runtime","currentComponentFileProcessingInformation","System","currentProcessingFileName"],"W":"timestampUpdated","V":null}
{"TS":1666597838599,"TP":["services","aws.greengrass.LogManager","runtime","currentComponentFileProcessingInformation","System","currentProcessingFileStartPosition"],"W":"timestampUpdated","V":null}
{"TS":1666597838599,"TP":["services","aws.greengrass.LogManager","runtime","currentComponentFileProcessingInformation","System","currentProcessingFileLastModified"],"W":"timestampUpdated","V":null}
{"TS":1666597838698,"TP":["services","aws.greengrass.LogManager","runtime","currentComponentFileProcessingInformation","box_configuration","currentProcessingFileName"],"W":"timestampUpdated","V":null}
{"TS":1666597838698,"TP":["services","aws.greengrass.LogManager","runtime","currentComponentFileProcessingInformation","box_configuration","currentProcessingFileStartPosition"],"W":"timestampUpdated","V":null}
{"TS":1666597838698,"TP":["services","aws.greengrass.LogManager","runtime","currentComponentFileProcessingInformation","box_configuration","currentProcessingFileLastModified"],"W":"timestampUpdated","V":null}
{"TS":1666597838698,"TP":["services","aws.greengrass.LogManager","runtime","currentComponentFileProcessingInformation","io.cognitohealth.DataGenerationV2","currentProcessingFileName"],"W":"timestampUpdated","V":null}
{"TS":1666597838698,"TP":["services","aws.greengrass.LogManager","runtime","currentComponentFileProcessingInformation","io.cognitohealth.DataGenerationV2","currentProcessingFileStartPosition"],"W":"timestampUpdated","V":null}
{"TS":1666597838698,"TP":["services","aws.greengrass.LogManager","runtime","currentComponentFileProcessingInformation","io.cognitohealth.DataGenerationV2","currentProcessingFileLastModified"],"W":"timestampUpdated","V":null}
{"TS":1666597838698,"TP":["services","aws.greengrass.LogManager","runtime","currentComponentFileProcessingInformation","System","currentProcessingFileName"],"W":"timestampUpdated","V":null}
{"TS":1666597838698,"TP":["services","aws.greengrass.LogManager","runtime","currentComponentFileProcessingInformation","System","currentProcessingFileStartPosition"],"W":"timestampUpdated","V":null}
{"TS":1666597838698,"TP":["services","aws.greengrass.LogManager","runtime","currentComponentFileProcessingInformation","System","currentProcessingFileLastModified"],"W":"timestampUpdated","V":null}
{"TS":1666597838756,"TP":["services","aws.greengrass.LogManager","runtime","currentComponentFileProcessingInformation","box_configuration","currentProcessingFileName"],"W":"timestampUpdated","V":null}
{"TS":1666597838756,"TP":["services","aws.greengrass.LogManager","runtime","currentComponentFileProcessingInformation","box_configuration","currentProcessingFileStartPosition"],"W":"timestampUpdated","V":null}
{"TS":1666597838756,"TP":["services","aws.greengrass.LogManager","runtime","currentComponentFileProcessingInformation","box_configuration","currentProcessingFileLastModified"],"W":"timestampUpdated","V":null}
{"TS":1666597838756,"TP":["services","aws.greengrass.LogManager","runtime","currentComponentFileProcessingInformation","io.cognitohealth.DataGenerationV2","currentProcessingFileName"],"W":"timestampUpdated","V":null}
{"TS":1666597838756,"TP":["services","aws.greengrass.LogManager","runtime","currentComponentFileProcessingInformation","io.cognitohealth.DataGenerationV2","currentProcessingFileStartPosition"],"W":"timestampUpdated","V":null}
{"TS":1666597838756,"TP":["services","aws.greengrass.LogManager","runtime","currentComponentFileProcessingInformation","io.cognitohealth.DataGenerationV2","currentProcessingFileLastModified"],"W":"timestampUpdated","V":null}
```

Output of `top` command:
```
top - 10:32:59 up 12 min,  1 user,  load average: 3.33, 3.35, 2.19
Tasks: 119 total,   1 running,  84 sleeping,   0 stopped,   0 zombie
%Cpu(s): 32.7 us, 62.1 sy,  0.0 ni,  0.0 id,  2.3 wa,  0.0 hi,  2.9 si,  0.0 st
KiB Mem :  1016304 total,     7424 free,   648096 used,   360784 buff/cache
KiB Swap:        0 total,        0 free,        0 used.   348336 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
  490 root       0 -20       0      0      0 I 43.5  0.0   2:46.83 kworker/0:4H
  886 root      20   0  322744  92888   8528 S 35.0  9.1   3:49.57 java
 1987 root      20   0   40720  25424   6800 S  6.0  2.5   0:24.73 python
  172 root      20   0       0      0      0 S  4.1  0.0   0:24.39 jbd2/mmcblk3p2-
 1813 ggc_user  20   0  286396  73936  12880 S  2.2  7.3   0:30.15 java
 1313 root      20   0   42304   5364   3516 S  1.9  0.5   0:13.76 chdemo
 2142 root      20   0    8520   2448   2048 R  0.9  0.2   0:00.10 top
    8 root      20   0       0      0      0 I  0.3  0.0   0:01.37 rcu_preempt
  331 root      20   0   27184     76      0 S  0.3  0.0   0:00.50 rngd
  361 root      20   0  949608  32912  14176 S  0.3  3.2   0:01.90 containerd
 1508 ggc_user  20   0  365004  38528  10508 S  0.3  3.8   0:07.88 java
```

**Environment**
 - OS: Debian 9
 - JDK version: OpenJDK8 (build 25.332-b09)
 - Nucleus version: 2.4.0
 - Log Manager version: 2.2.6

**Additional context**
It can't be solved by rebooting the device. The way to get rid of this situation is to remove LogManager and reboot device/restart greengrass. After that, the `currentComponentFileProcessingInformation` messages are stopped being written to config.tlog and kworker process will no longer occupy lots of CPU resources.

**Comment by jbutler** [comment]
HI @adamchen-cognitohealth - can you please share your LogManager configuration? Does the issue reproduce with the latest versions? (Nucleus 2.8 + LogManager 2.2.7)

**Comment by adamchen-cognitohealth** [comment]
Hi @jbutler - thanks for your reply. Below is part of the configuration of LogManager, format of the remaining are the same as the part. I didn't use the latest versions. (Nucleus 2.8 + LogManager 2.2.7)

```
---
componentVersion: 2.2.6

configurationUpdate:
  merge:
    periodicUploadIntervalSec: "600"
    logsUploaderConfiguration:
      systemLogsConfiguration:
        diskSpaceLimit: "10"
        diskSpaceLimitUnit: MB
        uploadToCloudWatch: "true"
        logFileRegex: "greengrass\\w+.log"
        minimumLogLevel: WARN
        deleteLogFileAfterCloudUpload: "true"

      componentLogsConfigurationMap:
        box_configuration:
          minimumLogLevel: WARN
          deleteLogFileAfterCloudUpload: "false"
          logFileRegex: "box_configuration.log.*"
          logFileDirectoryPath: /greengrass/v2/logs

        data_generation_v2:
          minimumLogLevel: WARN
          deleteLogFileAfterCloudUpload: "false"
          logFileRegex: "data_generation_v2.log.*"
          logFileDirectoryPath: /greengrass/v2/logs

        io.cognitohealth.BoxConfiguration:
          diskSpaceLimit: "10"
          diskSpaceLimitUnit: MB
          minimumLogLevel: WARN
          deleteLogFileAfterCloudUpload: "true"

        io.cognitohealth.DataGenerationV2:
          diskSpaceLimit: "10"
          diskSpaceLimitUnit: MB
          minimumLogLevel: WARN
          deleteLogFileAfterCloudUpload: "true"

        aws.greengrass.StreamManager:
          diskSpaceLimit: "10"
          diskSpaceLimitUnit: MB
          minimumLogLevel: WARN
          deleteLogFileAfterCloudUpload: "true"
```
